### ISSUE TITLE
Configurable root path

### ISSUE THREAD

**Issue by webworkerJoshua** [uiii/pw-core#1]
Hi @uiii,

is it possible to define the project's root path to something different than '.'?
https://github.com/uiii/pw-core/blob/c625cc7b925022d742be37b5b06a5dcda5cfb7b2/src/PW/Composer/Installer.php#L13-L17

In my case, the project root is './public'.
With https://github.com/harikt/pwmoduleinstaller it is possible to install PW modules in a specified sub-directory via the "pw-module-path" config within composer.json:
![grafik](https://user-images.githubusercontent.com/44984072/104349362-1f1a1d00-5503-11eb-913f-7e9ebde77196.png)
But I couldn't find a way to install ProcessWire via this composer module in the public directory.

**Comment by uiii** [comment]
Hi @webworkerJoshua, looks like a good idea. I'll look at it.

**Comment by uiii** [comment]
Where did you find the information about `pw-module-path`?

**Comment by webworkerJoshua** [comment]
Good question, I'm looking it up right now, where I got this info.
A quite similiar way seems to be integrated in [wireframe](https://wireframe-framework.com/docs/processwire-composer-installer/), but haven't tested this yet:
```
{
    "require": {
        ...
    },
    "extra": {
        "pw-module-path": "site/modules",
        "pw-site-profile-path": "",
    }
}
```

I'm searching for the reference right now ;)

**Comment by webworkerJoshua** [comment]
Looks like I already used **"wireframe-framework/processwire-composer-installer"** not "hari/pw-module" in my module - my mistake! Here you find the info: [wireframe-framework/processwire-composer-installer](https://packagist.org/packages/wireframe-framework/processwire-composer-installer). The info is also in their [docs](https://wireframe-framework.com/docs/processwire-composer-installer/)

**Comment by uiii** [comment]
Ah I see, so it is not Composer's magic :D just a manual work. I will inspire and do it here as well.

**Comment by uiii** [comment]
It is done 🎉 . Check it please.

**Comment by webworkerJoshua** [comment]
Nice, thank you! I will check it tomorrow morning.

**Comment by webworkerJoshua** [comment]
Checked it - it works perfectly!
Thanks alot :-)
